/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useState } from "react";

import {
  Sandpack,
  SandpackCodeEditor,
  SandpackFileExplorer,
  SandpackLayout,
  SandpackProvider,
} from "./index";
import { useSandpackFS } from "./utils/storyHelpers";

export default {
  title: "Bug reports/Issues",
};

export const FlushServerVsClient = (): JSX.Element | null => {
  const fs = useSandpackFS();
  if (!fs) return null;
  return (
    <SandpackProvider fs={fs}>
      <div style={{ border: "1px solid black" }}>
        <SandpackCodeEditor />
      </div>
    </SandpackProvider>
  );
};

export const Issue663 = (): JSX.Element | null => {
  const fs = useSandpackFS({ template: "react-ts" });
  if (!fs) return null;
  return (
    <Sandpack
      fs={fs}
      options={{
        showTabs: true,
        activeFile: "/index.tsx",
      }}
    />
  );
};

export const Issue482 = (): JSX.Element | null => {
  const [hidden, setHidden] = useState(false);

  const toggleHidden = (): void => {
    setHidden((prevHidden) => !prevHidden);
  };

  const fs = useSandpackFS({
    template: "vanilla",
    customSetup: {
      entry: "/index.js",
    },
    files: {
      "/index.js": {
        code: "// index.js",
        active: true,
      },
      "/index2.js": {
        code: "// index2.js",
      },
      "/src/index.js": {
        code: "// this file is generated by vanilla template, but it is not needed",
        hidden: true,
      },
      "/hidden.js": {
        code: "// hidden.js",
        hidden: true,
      },
    },
  });
  if (!fs) return null;

  return (
    <>
      <button onClick={toggleHidden}>toggle hidden</button>
      <SandpackProvider
        fs={fs}
        options={{
          visibleFiles: ["/index.js", "/hidden.js"],
          activeFile: "/index.js",
        }}
      >
        <SandpackLayout>
          <SandpackFileExplorer autoHiddenFiles={hidden} />
          <SandpackCodeEditor />
        </SandpackLayout>
      </SandpackProvider>
    </>
  );
};

export const Issue454 = (): JSX.Element | null => {
  const [readOnly, setReadOnly] = useState(false);
  const fs = useSandpackFS();
  if (!fs) return null;

  return (
    <>
      <button
        className="trigger"
        onClick={(): any => setReadOnly((prev) => !prev)}
      >
        click
      </button>
      <Sandpack fs={fs} options={{ readOnly }} />
    </>
  );
};

export const FileTab = (): JSX.Element | null => {
  const fs = useSandpackFS({ template: "react" });
  if (!fs) return null;
  return (
    <Sandpack
      fs={fs}
      options={{ visibleFiles: ["/App.js", "/styles.css"] }}
    />
  );
};

export const ReactRouter = (): JSX.Element | null => {
  const fs = useSandpackFS({
    template: "react",
    customSetup: {
      dependencies: {
        "react-router-dom": "^5.3.0",
      },
    },
    files: {
      "/App.js": `import React from "react";
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link
} from "react-router-dom";

export default function BasicExample() {
  return (
    <Router>
      <div>
        <ul>
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/about">About</Link>
          </li>
          <li>
            <Link to="/dashboard">Dashboard</Link>
          </li>
        </ul>

        <hr />

        <Switch>
          <Route exact path="/">
            <Home />
          </Route>
          <Route path="/about">
            <About />
          </Route>
          <Route path="/dashboard">
            <Dashboard />
          </Route>
        </Switch>
      </div>
    </Router>
  );
}

function Home() {
  return (
    <div>
      <h2>Home</h2>
    </div>
  );
}

function About() {
  return (
    <div>
      <h2>About</h2>
    </div>
  );
}

function Dashboard() {
  return (
    <div>
      <h2>Dashboard</h2>
    </div>
  );
}
`,
    },
  });
  if (!fs) return null;
  return (
    <Sandpack fs={fs} options={{ showNavigator: true }} />
  );
};
